### ISSUE TITLE
Panic for invalid strings

### ISSUE THREAD

**Issue by 29ayush** [daku10/go-lz-string#29]
If I try to decode string "No" for example I run into panic
https://go.dev/play/p/0rF2U4cLjce

Can you please return an error instead of panicking

**Comment by daku10** [comment]
@29ayush 
Thanks for flagging this with the Go Playground link! Seeing a panic when decoding a string like "No" is definitely not ideal.

I created a new release with a fix for this issue. 
[Fix for this issue](https://github.com/daku10/go-lz-string/pull/30)
[New Release](https://github.com/daku10/go-lz-string/releases/tag/v0.0.6)

Please try it out and let me know if you still see the same issue.
Thanks again for pointing this out!

**Comment by 29ayush** [comment]
Awesome, thanks for the quick fix :)
